import type { HzdKyxDesktopApi } from "../../../preload";
import type {
  AppNotificationListResult,
  CloudSyncAutoSyncStatus,
  CloudSyncSettingsView,
  GameMarketSettingsView,
  GameMarketPollingStatus,
  WebhookServerSettingsView,
} from "../../../shared/contracts";
import { emptyProfitListResult } from "../../../shared/profit-analysis";

const unavailable = async (): Promise<never> => {
  throw new Error("Electron preload indisponível no preview web.");
};

const unavailableElectronProfit = async (): Promise<never> => {
  throw new Error(
    "Módulo de lucro indisponível no preload. Reinicie o app para carregar a versão atual.",
  );
};

const buildProfitApi = (
  api: Partial<HzdKyxDesktopApi> | undefined,
): HzdKyxDesktopApi["profit"] => {
  const profitApi = (api?.profit ?? {}) as Partial<HzdKyxDesktopApi["profit"]>;

  return {
    list:
      typeof profitApi.list === "function"
        ? profitApi.list
        : unavailableElectronProfit,
    exportCsv:
      typeof profitApi.exportCsv === "function"
        ? profitApi.exportCsv
        : unavailableElectronProfit,
  };
};

const fallbackApi: HzdKyxDesktopApi = {
  getAppMeta: async () => ({
    name: "HzdKyx GameMarket Manager",
    version: "0.1.0",
    platform: "win32",
  }),
  getDatabaseStatus: async () => ({
    path: "Electron preload indisponível no preview web.",
    connected: false,
    appliedMigrations: [],
  }),
  showNotification: async () => ({
    shown: false,
    reason: "Notificações desktop exigem execução no Electron.",
  }),
  startup: {
    markRendererReady: () => undefined,
  },
  notifications: {
    onCreated: () => () => undefined,
    onOpenOrder: () => () => undefined,
    onFallback: () => () => undefined,
  },
  appNotifications: {
    list: async (): Promise<AppNotificationListResult> => ({
      items: [],
      summary: {
        total: 0,
        unread: 0,
        unreadNewSales: 0,
        criticalUnread: 0,
      },
    }),
    markRead: unavailable,
    markAllRead: async () => ({ updated: 0 }),
    testNotification: async () => ({
      shown: false,
      reason: "Notificações locais exigem execução no Electron.",
    }),
  },
  auth: {
    getBootstrap: async () => ({
      hasAdmin: true,
      session: null,
    }),
    setupAdmin: unavailable,
    login: unavailable,
    logout: async () => ({ loggedOut: true }),
    getSession: async () => null,
    changeOwnPassword: unavailable,
  },
  users: {
    list: async () => [],
    create: unavailable,
    update: unavailable,
    resetPassword: unavailable,
  },
  products: {
    list: async () => ({
      items: [],
      summary: {
        total: 0,
        active: 0,
        outOfStock: 0,
        lowStock: 0,
        averageEstimatedProfit: 0,
      },
      categories: [],
    }),
    get: unavailable,
    create: unavailable,
    update: unavailable,
    delete: unavailable,
    exportCsv: async () => ({
      filename: "hzdk-products.csv",
      content: "",
    }),
  },
  productVariants: {
    listByProduct: async () => ({
      items: [],
    }),
    get: unavailable,
    create: unavailable,
    update: unavailable,
    duplicate: unavailable,
    archive: unavailable,
    markNeedsReview: unavailable,
    delete: unavailable,
    exportCsv: async () => ({
      filename: "hzdk-product-variants.csv",
      content: "",
    }),
  },
  inventory: {
    list: async () => ({
      items: [],
      summary: {
        available: 0,
        sold: 0,
        problem: 0,
        totalCost: 0,
        potentialProfit: 0,
      },
      protectedSummary: {
        available: 0,
        sold: 0,
        problem: 0,
        totalCost: 0,
        potentialProfit: 0,
      },
      operationalItems: [],
      operationalSummary: {
        available: 0,
        sold: 0,
        problem: 0,
        totalCost: 0,
        potentialProfit: 0,
        lowStock: 0,
        outOfStock: 0,
        productRows: 0,
        variantRows: 0,
      },
      products: [],
      productVariants: [],
      suppliers: [],
      categories: [],
    }),
    get: unavailable,
    create: unavailable,
    update: unavailable,
    delete: unavailable,
    revealSecret: unavailable,
    exportCsv: async () => ({
      filename: "hzdk-inventory.csv",
      content: "",
    }),
  },
  orders: {
    list: async () => ({
      items: [],
      summary: {
        total: 0,
        pendingAction: 0,
        problemOrMediation: 0,
        grossRevenue: 0,
        netRevenue: 0,
        estimatedProfit: 0,
      },
      products: [],
      productVariants: [],
      inventoryItems: [],
      categories: [],
    }),
    get: unavailable,
    create: unavailable,
    update: unavailable,
    delete: unavailable,
    archive: unavailable,
    changeStatus: unavailable,
    linkInventoryItem: unavailable,
    unlinkInventoryItem: unavailable,
    exportCsv: async () => ({
      filename: "hzdk-orders.csv",
      content: "",
    }),
  },
  events: {
    list: async () => ({
      items: [],
      summary: {
        total: 0,
        unread: 0,
        critical: 0,
        warnings: 0,
      },
      types: [],
    }),
    get: unavailable,
    markRead: unavailable,
    markAllRead: async () => ({ updated: 0 }),
    createManual: unavailable,
    exportCsv: async () => ({
      filename: "hzdk-events.csv",
      content: "",
    }),
  },
  profit: {
    list: async () => emptyProfitListResult,
    exportCsv: async () => ({
      filename: "hzdk-profit-analysis.csv",
      content: "",
    }),
  },
  dashboard: {
    getSummary: async () => ({
      salesToday: 0,
      salesMonth: 0,
      grossRevenueMonth: 0,
      netRevenueMonth: 0,
      estimatedProfitMonth: 0,
      pendingActionOrders: 0,
      problemOrMediationOrders: 0,
      lowStockProducts: 0,
      outOfStockProducts: 0,
      unreadNewSales: 0,
      deliveredAwaitingRelease: 0,
      waitingReleaseCount: 0,
      waitingReleaseGross: 0,
      waitingReleaseNet: 0,
      waitingReleaseProfit: 0,
      gameMarketApiConfigured: false,
      gameMarketPollingActive: false,
      gameMarketLastCheckedAt: null,
      gameMarketNextRunAt: null,
      gameMarketLastPollingStatus: "not_configured",
      gameMarketLastPollingMessage: null,
      latestEvents: [],
      salesByDay: [],
      profitByCategory: [],
      statusBreakdown: [],
    }),
  },
  settings: {
    getNotificationSettings: async () => ({
      desktopEnabled: true,
      localNotificationsEnabled: true,
      soundEnabled: true,
      soundVolume: 0.7,
      showWhenMinimized: true,
      automaticPollingEnabled: true,
      pollingIntervalSeconds: 60,
      notifyNewSale: true,
      notifyMediationProblem: true,
      notifyOrderDelivered: true,
      notifyOrderCompleted: true,
      enabledEventTypes: {},
    }),
    updateNotificationSettings: async (payload) => ({
      desktopEnabled:
        payload.localNotificationsEnabled ?? payload.desktopEnabled ?? true,
      localNotificationsEnabled:
        payload.localNotificationsEnabled ?? payload.desktopEnabled ?? true,
      soundEnabled: payload.soundEnabled ?? true,
      soundVolume: payload.soundVolume ?? 0.7,
      showWhenMinimized: payload.showWhenMinimized ?? true,
      automaticPollingEnabled: payload.automaticPollingEnabled ?? true,
      pollingIntervalSeconds: payload.pollingIntervalSeconds ?? 60,
      notifyNewSale: payload.notifyNewSale ?? true,
      notifyMediationProblem: payload.notifyMediationProblem ?? true,
      notifyOrderDelivered: payload.notifyOrderDelivered ?? true,
      notifyOrderCompleted: payload.notifyOrderCompleted ?? true,
      enabledEventTypes: payload.enabledEventTypes ?? {},
    }),
  },
  gamemarket: {
    getSettings: async (): Promise<GameMarketSettingsView> => ({
      apiBaseUrl: "https://gamemarket.com.br",
      integrationName: "HzdKyx Desktop",
      environment: "production",
      hasToken: false,
      tokenMasked: null,
      tokenSource: "none",
      connectionStatus: "not_configured",
      lastConnectionAt: null,
      lastSyncAt: null,
      lastError: null,
      documentation: {
        status: "missing",
        files: [],
        missing: ["docs/gamemarket-api/"],
        message: "Electron preload indisponível no preview web.",
      },
      permissions: {
        read: true,
        write: false,
        delete: false,
        source: "documentation",
      },
    }),
    updateSettings: unavailable,
    revealToken: unavailable,
    testConnection: async () => ({
      ok: false,
      status: "unavailable",
      checkedAt: new Date().toISOString(),
      endpoint: null,
      safeMessage: "Teste exige execução no Electron.",
    }),
    syncNow: async () => ({
      startedAt: new Date().toISOString(),
      finishedAt: new Date().toISOString(),
      durationMs: 0,
      status: "failed",
      productsFound: 0,
      ordersFound: 0,
      productsNew: 0,
      productsUpdated: 0,
      ordersNew: 0,
      ordersUpdated: 0,
      errors: ["Sync exige execução no Electron."],
    }),
    pollNow: async (): Promise<GameMarketPollingStatus> => ({
      active: false,
      running: false,
      intervalSeconds: 60,
      startedAt: null,
      finishedAt: null,
      status: "not_configured",
      importedOrders: 0,
      updatedOrders: 0,
      errors: ["Polling exige execução no Electron."],
      nextRunAt: null,
      lastResult: "Polling exige execução no Electron.",
    }),
    getPollingStatus: async (): Promise<GameMarketPollingStatus> => ({
      active: false,
      running: false,
      intervalSeconds: 60,
      startedAt: null,
      finishedAt: null,
      status: "not_configured",
      importedOrders: 0,
      updatedOrders: 0,
      errors: ["Polling exige execução no Electron."],
      nextRunAt: null,
      lastResult: "Polling exige execução no Electron.",
    }),
    getLastSyncSummary: async () => null,
  },
  webhookServer: {
    getSettings: async (): Promise<WebhookServerSettingsView> => ({
      backendUrl: "http://localhost:3001",
      hasToken: false,
      tokenMasked: null,
      connectionStatus: "not_configured",
      pollingEnabled: false,
      pollingIntervalSeconds: 60,
      lastCheckedAt: null,
      lastSyncAt: null,
      lastEventReceivedAt: null,
      lastError: "Electron preload indisponível no preview web.",
    }),
    updateSettings: unavailable,
    revealToken: unavailable,
    testConnection: async () => ({
      ok: false,
      status: "unavailable",
      checkedAt: new Date().toISOString(),
      endpoint: null,
      safeMessage: "Teste exige execução no Electron.",
    }),
    sendTestEvent: async () => ({
      ok: false,
      id: "",
      eventType: "gamemarket.unknown",
      severity: "warning",
      message: "Teste exige execução no Electron.",
    }),
    syncEventsNow: async () => ({
      startedAt: new Date().toISOString(),
      finishedAt: new Date().toISOString(),
      durationMs: 0,
      status: "failed",
      eventsFound: 0,
      eventsImported: 0,
      eventsAcked: 0,
      duplicatesSkipped: 0,
      notificationsTriggered: 0,
      errors: ["Sync exige execução no Electron."],
    }),
    getLastSyncSummary: async () => null,
  },
  cloudSync: {
    getSettings: async (): Promise<CloudSyncSettingsView> => ({
      backendUrl: "http://localhost:3001",
      mode: "local",
      connectionStatus: "not_configured",
      hasSession: false,
      currentUser: null,
      workspaces: [],
      workspaceId: null,
      workspaceName: null,
      workspaceRole: null,
      autoSyncEnabled: true,
      syncIntervalSeconds: 30,
      lastSyncAt: null,
      lastPullAt: null,
      lastPushAt: null,
      lastError: "Electron preload indisponível no preview web.",
      pendingChanges: 0,
      conflictCount: 0,
    }),
    updateSettings: unavailable,
    testConnection: async () => ({
      ok: false,
      safeMessage: "Teste exige execução no Electron.",
    }),
    bootstrapOwner: unavailable,
    login: unavailable,
    logout: unavailable,
    refreshAccount: unavailable,
    listMembers: async () => [],
    inviteUser: unavailable,
    updateMember: unavailable,
    publishLocalData: async () => ({
      startedAt: new Date().toISOString(),
      finishedAt: new Date().toISOString(),
      durationMs: 0,
      status: "failed",
      collected: 0,
      pushed: 0,
      pulled: 0,
      applied: 0,
      conflicts: 0,
      ignored: 0,
      skipped: 0,
      entityTypes: [],
      errors: ["Sync exige execução no Electron."],
    }),
    downloadWorkspace: async () => ({
      startedAt: new Date().toISOString(),
      finishedAt: new Date().toISOString(),
      durationMs: 0,
      status: "failed",
      collected: 0,
      pushed: 0,
      pulled: 0,
      applied: 0,
      conflicts: 0,
      ignored: 0,
      skipped: 0,
      entityTypes: [],
      errors: ["Sync exige execução no Electron."],
    }),
    syncNow: async () => ({
      startedAt: new Date().toISOString(),
      finishedAt: new Date().toISOString(),
      durationMs: 0,
      status: "failed",
      collected: 0,
      pushed: 0,
      pulled: 0,
      applied: 0,
      conflicts: 0,
      ignored: 0,
      skipped: 0,
      entityTypes: [],
      errors: ["Sync exige execução no Electron."],
    }),
    getLastSyncSummary: async () => null,
    getAutoSyncStatus: async (): Promise<CloudSyncAutoSyncStatus> => ({
      active: false,
      paused: false,
      running: false,
      intervalSeconds: 30,
      minIntervalSeconds: 10,
      startedAt: null,
      finishedAt: null,
      nextRunAt: null,
      status: "not_configured",
      lastResult: "Electron preload indisponível no preview web.",
      pendingChanges: 0,
      failureCount: 0,
      backoffSeconds: null,
    }),
    pauseAutoSync: async (): Promise<CloudSyncAutoSyncStatus> => ({
      active: false,
      paused: true,
      running: false,
      intervalSeconds: 30,
      minIntervalSeconds: 10,
      startedAt: null,
      finishedAt: null,
      nextRunAt: null,
      status: "paused",
      lastResult: "Sync automático pausado no preview.",
      pendingChanges: 0,
      failureCount: 0,
      backoffSeconds: null,
    }),
    resumeAutoSync: async (): Promise<CloudSyncAutoSyncStatus> => ({
      active: false,
      paused: false,
      running: false,
      intervalSeconds: 30,
      minIntervalSeconds: 10,
      startedAt: null,
      finishedAt: null,
      nextRunAt: null,
      status: "not_configured",
      lastResult: "Sync automático exige execução no Electron.",
      pendingChanges: 0,
      failureCount: 0,
      backoffSeconds: null,
    }),
  },
};

const mergeDesktopApi = (
  api: Partial<HzdKyxDesktopApi> | undefined,
): HzdKyxDesktopApi => ({
  ...fallbackApi,
  ...api,
  notifications: {
    ...fallbackApi.notifications,
    ...api?.notifications,
  },
  startup: {
    ...fallbackApi.startup,
    ...api?.startup,
  },
  appNotifications: {
    ...fallbackApi.appNotifications,
    ...api?.appNotifications,
  },
  auth: {
    ...fallbackApi.auth,
    ...api?.auth,
  },
  users: {
    ...fallbackApi.users,
    ...api?.users,
  },
  products: {
    ...fallbackApi.products,
    ...api?.products,
  },
  productVariants: {
    ...fallbackApi.productVariants,
    ...api?.productVariants,
  },
  inventory: {
    ...fallbackApi.inventory,
    ...api?.inventory,
  },
  orders: {
    ...fallbackApi.orders,
    ...api?.orders,
  },
  events: {
    ...fallbackApi.events,
    ...api?.events,
  },
  profit: buildProfitApi(api),
  dashboard: {
    ...fallbackApi.dashboard,
    ...api?.dashboard,
  },
  settings: {
    ...fallbackApi.settings,
    ...api?.settings,
  },
  gamemarket: {
    ...fallbackApi.gamemarket,
    ...api?.gamemarket,
  },
  webhookServer: {
    ...fallbackApi.webhookServer,
    ...api?.webhookServer,
  },
  cloudSync: {
    ...fallbackApi.cloudSync,
    ...api?.cloudSync,
  },
});

export const getDesktopApi = (): HzdKyxDesktopApi =>
  window.hzdk ? mergeDesktopApi(window.hzdk) : fallbackApi;
